# Titel
title: Christen helfen in Rumänien Baierbronn 

# Eine 1-Satz Beschreibung
tagline: Wir sind eine christliche Gruppe aus Baierbronn und helfen in Rumänien. 

# Beschreibung (wird als Titel benutzt wenn kein TITLE verwendet wird)
description: Teile mit dem Hungrigen dein Brot (Jesaja 58,7). Nach diesem Leitsatz unterstützen wir als 
Christen aus Baiersbronn in Rumänien mit regelmäßigen Hilfstransporten.



